# ---------------------------------------------------------------------------
# Makefile for the Mini Language Compiler (CSE 416 Compiler Construction Lab
# Project). Builds a single executable: bin/mycompiler
#
# Usage:
#   make          -> builds bin/mycompiler
#   make run FILE=examples/sample1.mc  -> builds (if needed) and runs it
#   make clean    -> removes all generated files
# ---------------------------------------------------------------------------

CC      = gcc
CFLAGS  = -Wall -Wno-unused-function -g -Isrc
LEX     = flex
YACC    = bison

BIN_DIR = bin
BUILD_DIR = build

# Files generated by Bison/Flex live in build/ so they never get committed
# to the wrong place and are easy to .gitignore.
PARSER_C = $(BUILD_DIR)/parser.tab.c
PARSER_H = $(BUILD_DIR)/parser.tab.h
LEXER_C  = $(BUILD_DIR)/lex.yy.c

SRCS = src/main.c \
       src/ast/ast.c \
       src/symbol_table/symbol_table.c \
       src/semantic/semantic.c \
       src/codegen/codegen.c \
       $(PARSER_C) \
       $(LEXER_C)

OBJS = $(patsubst %.c,$(BUILD_DIR)/%.o,$(notdir $(SRCS)))

TARGET = $(BIN_DIR)/mycompiler

.PHONY: all clean run dirs

all: dirs $(TARGET)

dirs:
	@mkdir -p $(BIN_DIR) $(BUILD_DIR)

# Bison must run before Flex, because lexer.l includes parser.tab.h.
$(PARSER_C) $(PARSER_H): src/parser/parser.y | dirs
	$(YACC) -d -o $(PARSER_C) $<

$(LEXER_C): src/lexer/lexer.l $(PARSER_H) | dirs
	$(LEX) -o $(LEXER_C) $<

# Generic pattern rules: compile every .c we care about into build/*.o
$(BUILD_DIR)/main.o: src/main.c | dirs
	$(CC) $(CFLAGS) -I$(BUILD_DIR) -c $< -o $@

$(BUILD_DIR)/ast.o: src/ast/ast.c | dirs
	$(CC) $(CFLAGS) -c $< -o $@

$(BUILD_DIR)/symbol_table.o: src/symbol_table/symbol_table.c | dirs
	$(CC) $(CFLAGS) -c $< -o $@

$(BUILD_DIR)/semantic.o: src/semantic/semantic.c | dirs
	$(CC) $(CFLAGS) -c $< -o $@

$(BUILD_DIR)/codegen.o: src/codegen/codegen.c | dirs
	$(CC) $(CFLAGS) -c $< -o $@

$(BUILD_DIR)/parser.tab.o: $(PARSER_C) | dirs
	$(CC) $(CFLAGS) -I$(BUILD_DIR) -c $< -o $@

$(BUILD_DIR)/lex.yy.o: $(LEXER_C) | dirs
	$(CC) $(CFLAGS) -I$(BUILD_DIR) -c $< -o $@

$(TARGET): $(BUILD_DIR)/main.o $(BUILD_DIR)/ast.o $(BUILD_DIR)/symbol_table.o \
           $(BUILD_DIR)/semantic.o $(BUILD_DIR)/codegen.o \
           $(BUILD_DIR)/parser.tab.o $(BUILD_DIR)/lex.yy.o | dirs
	$(CC) $(CFLAGS) -o $@ $^ -lfl

run: all
	./$(TARGET) $(FILE)

clean:
	rm -rf $(BUILD_DIR) $(BIN_DIR)
